#Habilitando dependencias

#Para MariaDB
mariadb:
  metrics:
    enable: false
    serviceMonitor:
      enable: true
#Para Elasticsearch
eck-operator:
  metrics:
    enable: false
    serviceMonitor:
      enable: true
#Para PostgreSql
postgresql:
  metrics:
    enable: false
    serviceMonitor:
      enable: true
#Para MongoDB
mongodb:
  metrics:
    enable: false
    serviceMonitor:
      enable: true
#Para Prometheus
kube-prometheus:
  metrics:
    enable: false
    serviceMonitor:
      enable: true
#Para Grafana
grafana:
  metrics:
    enable: false
    serviceMonitor:
      enable: true
