enableMariaDB: true 

mariadb:
    architecture: replication
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
    auth:
        database: tarea
        rootPassword: admin
        username: usuario
        password: passusuario
        replicationPassword: passreplica
    secondary:
        replicaCount: 2