#Habilitando dependencias

#Para MariaDB
mariadb:
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
#Para Elasticsearch
eck-operator:
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
#Para PostgreSql
postgresql:
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
#Para MongoDB
mongodb:
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
#Para Prometheus
kube-prometheus:
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
#Para Grafana
grafana:
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
